{
    "code": 0,
    "msg": "ok",
    "data": [
        {
            "exists": true,
            "name": "l4m2",
            "code": "5E1FB018E3",
            "alias": "",
            "description": "本网站高危测试解决号",
            "homepageUrl": "/u/5E1FB018E3",
            "group": 4,
            "groupName": "管理员",
            "isLocked": false,
            "gender": 0,
            "avatarUrl": "/common/person.jpg",
            "realName": "",
            "refBaike": "",
            "isManager": true,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2015-05-30 20:11:49"
        },
        {
            "exists": true,
            "name": "3067895430",
            "code": "8C5186A36F",
            "alias": "jp",
            "description": "姜盼",
            "homepageUrl": "/u/jp",
            "group": 2,
            "groupName": "实名用户",
            "isLocked": false,
            "gender": 0,
            "avatarUrl": "/user/29365f168942.jpg",
            "realName": "呵呵",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2016-02-06 19:07:35"
        },
        {
            "exists": true,
            "name": "孙天骁",
            "code": "admin",
            "alias": "stx",
            "description": "一个内心丰富的人",
            "homepageUrl": "/u/stx",
            "group": 5,
            "groupName": "站长",
            "isLocked": false,
            "gender": 1,
            "avatarUrl": "/s/user/FufL-vSFO5eM1we1mxdfYHKH9tfK.jpg",
            "realName": "孙天骁",
            "refBaike": "",
            "isManager": true,
            "isMe": true,
            "isLover": false,
            "introduction": "",
            "joinTime": "2015-02-11 21:45:00"
        },
        {
            "exists": true,
            "name": "摆渡人",
            "code": "0B3228F4AA",
            "alias": "",
            "description": "",
            "homepageUrl": "/u/0B3228F4AA",
            "group": 0,
            "groupName": "普通用户",
            "isLocked": false,
            "gender": 0,
            "avatarUrl": "/common/person.jpg",
            "realName": "谢元梅",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2023-08-28 19:47:51"
        },
        {
            "exists": true,
            "name": "GOOD_LUCK",
            "code": "99F80211YK",
            "alias": "yk",
            "description": "大学同学闫坤",
            "homepageUrl": "/u/yk",
            "group": 2,
            "groupName": "实名用户",
            "isLocked": false,
            "gender": 1,
            "avatarUrl": "/user/2f1924477c5d.jpg",
            "realName": "闫坤",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2017-07-01 15:39:47"
        },
        {
            "exists": true,
            "name": "lwjcs2018",
            "code": "68FA48D41C",
            "alias": "",
            "description": "咩仔",
            "homepageUrl": "/u/68FA48D41C",
            "group": 4,
            "groupName": "管理员",
            "isLocked": false,
            "gender": 1,
            "avatarUrl": "/common/person.jpg",
            "realName": "Stave咩",
            "refBaike": "",
            "isManager": true,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2023-07-14 13:25:35"
        },
        {
            "exists": true,
            "name": "王庭茂",
            "code": "44FB4C7WTM",
            "alias": "wtm",
            "description": "技术帝可乐",
            "homepageUrl": "/u/wtm",
            "group": 3,
            "groupName": "高级用户",
            "isLocked": false,
            "gender": 0,
            "avatarUrl": "/user/59e95a78679e.jpg",
            "realName": "王庭茂",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2014-08-18 11:55:31"
        },
        {
            "exists": true,
            "name": "耶瞳",
            "code": "81D2F09721",
            "alias": "",
            "description": "个人网站站长耶瞳",
            "homepageUrl": "/u/81D2F09721",
            "group": 1,
            "groupName": "认证用户",
            "isLocked": false,
            "gender": 1,
            "avatarUrl": "/s/user/FnMdqNmvvzP2sb9uqGe2roZcCQ8A.jpg",
            "realName": "",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2023-04-01 23:37:36"
        },
        {
            "exists": true,
            "name": "千言",
            "code": "27376A6D05",
            "alias": "",
            "description": "千言~",
            "homepageUrl": "/u/27376A6D05",
            "group": 2,
            "groupName": "实名用户",
            "isLocked": false,
            "gender": 1,
            "avatarUrl": "/common/person.jpg",
            "realName": "钱言",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2017-03-26 00:39:20"
        },
        {
            "exists": true,
            "name": "风行之灵",
            "code": "574DED13A5",
            "alias": "",
            "description": "",
            "homepageUrl": "/u/574DED13A5",
            "group": 0,
            "groupName": "普通用户",
            "isLocked": false,
            "gender": 1,
            "avatarUrl": "/common/person.jpg",
            "realName": "",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2023-01-30 00:31:02"
        },
        {
            "exists": true,
            "name": "Asea",
            "code": "53C316C8F8",
            "alias": "",
            "description": "",
            "homepageUrl": "/u/53C316C8F8",
            "group": 0,
            "groupName": "普通用户",
            "isLocked": false,
            "gender": 1,
            "avatarUrl": "/s/user/Fqv_HfBdxwXHM81qHk1OhI1JurWs.jpg",
            "realName": "高远",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2023-03-11 00:57:26"
        },
        {
            "exists": true,
            "name": "白木",
            "code": "37F8666B7D",
            "alias": "",
            "description": "",
            "homepageUrl": "/u/37F8666B7D",
            "group": 0,
            "groupName": "普通用户",
            "isLocked": false,
            "gender": 1,
            "avatarUrl": "/s/user/FrDupK_xCbN6ihvg7ggRoOFVum6E.jpg",
            "realName": "",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2022-08-22 16:55:21"
        },
        {
            "exists": true,
            "name": "Kaza",
            "code": "8E5559A9CD",
            "alias": "",
            "description": "",
            "homepageUrl": "/u/8E5559A9CD",
            "group": 0,
            "groupName": "普通用户",
            "isLocked": false,
            "gender": 1,
            "avatarUrl": "/user/e3e392dd5b6a.jpg",
            "realName": "",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2023-02-21 01:46:50"
        },
        {
            "exists": true,
            "name": "阿举",
            "code": "8706671BCD",
            "alias": "",
            "description": "张兴举，个人网站站长",
            "homepageUrl": "/u/8706671BCD",
            "group": 2,
            "groupName": "实名用户",
            "isLocked": false,
            "gender": 1,
            "avatarUrl": "/user/c04d1e171128.jpg",
            "realName": "张兴举",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2016-04-21 13:52:01"
        },
        {
            "exists": true,
            "name": "林文韬",
            "code": "182C734FBE",
            "alias": "lwt",
            "description": "小米同事林文韬",
            "homepageUrl": "/u/lwt",
            "group": 2,
            "groupName": "实名用户",
            "isLocked": false,
            "gender": 1,
            "avatarUrl": "/common/person.jpg",
            "realName": "林文韬",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2021-10-09 08:21:26"
        },
        {
            "exists": true,
            "name": "丹枫路乔治",
            "code": "58EFA73E1F",
            "alias": "",
            "description": "",
            "homepageUrl": "/u/58EFA73E1F",
            "group": 0,
            "groupName": "普通用户",
            "isLocked": false,
            "gender": 1,
            "avatarUrl": "/common/person.jpg",
            "realName": "",
            "refBaike": "",
            "isManager": false,
            "isMe": false,
            "isLover": false,
            "introduction": "",
            "joinTime": "2022-11-16 16:29:04"
        }
    ]
}